import Head from 'next/head'
import { ClerkProvider, useUser, useAuth, SignIn, SignedOut, SignedIn} from '@clerk/nextjs'

export default function Home() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>
        Sarah's To-do App
      </h1>
      <SignedOut>
        <SignIn />
      </SignedOut>
      <SignedIn>
        <div>hey</div>
      </SignedIn>
    </>
  )
}
