import Head from 'next/head'
import { useState, useEffect } from "react"
import TodoList from '@/components/TodoList'
import Link from 'next/link'

export default function DoneTodos() {
  const API_ENDPOINT = "https://backend-ahul.api.codehooks.io/dev/todos?done=true"
  const API_KEY = "e54ecd9c-02c3-481f-a9ca-de4d5d6ecaa7"

  // Set states
  const [todos, setTodos] = useState(null);
  const [loading, setLoading] = useState(true);

  // Get done todos
  useEffect(() => {
    const fetchData = async () => {
      try{
        const response = await fetch(API_ENDPOINT, {
          'method':'GET',
          'headers': {'x-apikey': API_KEY}
        });
        const data = await response.json();
        console.log("Data: ", data);

        // Update state
        setTodos(data);
        setLoading(false);
      }
      catch(err){
        console.log("Error: ", err);
      }
    }
    fetchData();
  }, [])

  if(loading){
    console.log("Loading")
  }
  else{
    console.log("Todos: ", todos);
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="header">
          Done To-dos
        </h1>
        <TodoList todoItems={todos}></TodoList>
        <Link href="/todos"><button>View Not Done To-dos</button></Link>
      </>
    )
  }
}
