import Head from 'next/head'
import { useState, useEffect } from "react"
import { useAuth } from "@clerk/nextjs";
import TodoList from '@/components/TodoList'
import Link from 'next/link'
import { getTodos } from "@/modules/Data";


export default function DoneTodos() {
  const { isLoaded, userId, sessionId, getToken } = useAuth();
  
  // Set states
  const [todos, setTodos] = useState(null);
  const [loading, setLoading] = useState(true);

  // Get done todos
  useEffect(() => {
    async function doneTodos() {
      if (userId) {
        const token = await getToken({ template: "codehooks" });
        setTodos(await getTodos(token, true));
        setLoading(false);
      }
    }
    doneTodos();
  }, [isLoaded]);

  if(loading){
    console.log("Loading")
  }
  else{
    console.log("Todos: ", todos);
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="header">
          Done To-dos
        </h1>
        <TodoList todoItems={todos}></TodoList>
        <Link href="/todos"><button>View Not Done To-dos</button></Link>
      </>
    )
  }
}
