import Head from 'next/head'
import TodoList from '@/components/TodoList'
import Link from 'next/link'

export default function DoneTodos() {
  const mockTodos = [{id: 1, content: "Clean room"}, {id: 2, content: "Wash dishes"}]
  // maybe add a status key --> done/not-done
  // event.stopPropagation();


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 class="header">
        Done To-dos
      </h1>

      {/* mockTodos should be replaced with only done todos in db */}
      <TodoList todoItems={mockTodos}></TodoList>
      <Link href="/todos"><button>View Not Done To-dos</button></Link>
    </>
  )
}
