import Head from 'next/head'
import { Inter } from 'next/font/google'
import TodoList from '@/components/TodoList'
import AddTodoItem from '@/components/AddTodoItem'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function NotDoneTodos() {
  const mockTodos = [{id: 1, content: "Clean room"}, {id: 2, content: "Wash dishes"}]
  // maybe add a status key --> done/not-done

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 class="header">
        To-do List
      </h1>
      
      {/* mockTodos should be replaced with only done todos in db */}
      <TodoList todoItems={mockTodos}></TodoList>
      <Link href="/done"><button>View Done To-do Items</button></Link>
      <AddTodoItem></AddTodoItem>
    </>
  )
}