import Head from 'next/head'
import { Inter } from 'next/font/google'
import { useState, useEffect } from "react"
import TodoList from '@/components/TodoList'
import AddTodoItem from '@/components/AddTodoItem'
import Link from 'next/link'


const inter = Inter({ subsets: ['latin'] })

export default function NotDoneTodos() {
  const mockTodos = [{id: 1, content: "Clean room"}, {id: 2, content: "Wash dishes"}]
  // maybe add a status key --> done/not-done

  const API_ENDPOINT = "https://backend-ahul.api.codehooks.io/dev/todos"
  const API_KEY = "e54ecd9c-02c3-481f-a9ca-de4d5d6ecaa7"

  // Set states
  const [todos, setTodos] = useState(null);
  const [loading, setLoading] = useState(true);

  // Get todos
  useEffect(() => {
    const fetchData = async () => {
      try{
        const response = await fetch(API_ENDPOINT, {
          'method':'GET',
          'headers': {'x-apikey': API_KEY}
        });
        const data = await response.json();
        console.log("Data: ", data);

        // Update state
        setTodos(data);
        setLoading(false);
      }
      catch(err){
        console.log("Error: ", err);
      }
    }
    fetchData();
  }, [])


  if(loading){
    console.log("Loading")
  }
  else{
    console.log("Todos: ", todos);
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="header">
          To-do List
        </h1>
        
        {/* mockTodos should be replaced with only not done todos in db */}
        <TodoList todoItems={todos}></TodoList>
        <Link href="/done"><button>View Done To-do Items</button></Link>
        <AddTodoItem></AddTodoItem>
      </>
    )
  }
}